// JSON formatında Almanca ve İngilizce kelimeler
let flashcards = [
    { question: "Abitur (Sg.)", answer: "high school graduation exam" },
    { question: "Absage - n", answer: "Cancellation" },
    { question: "Actionfilm - e", answer: "Action Film" },
    { question: "Ahnung - en", answer: "Idea" },
    { question: "Altenpfleger -", answer: "Elderly Care Nurse (masc.)" },
    { question: "Altenpflegerin - nen", answer: "Elderly Care Nurse (fem.)" },
    { question: "anbieten", answer: "to offer" },
    { question: "ander", answer: "different" },
    { question: "Angst haben", answer: "to fear" },
    { question: "anklicken", answer: "to click on" },
    { question: "anmachen", answer: "to turn (something) on" },
    { question: "anprobieren", answer: "to try on" },
    { question: "Arbeitsgemeinschaft", answer: "Working Team" },
    { question: "ärgerlich", answer: "angry" },
    { question: "Arztpraxis, die Arztpraxen", answer: "Doctor's Office" },
    { question: "Aschluss -: e", answer: "Degree" },
    { question: "aufgeregt sein", answer: "to be excited" },
    { question: "aufpassen", answer: "to watch out" },
    { question: "aufregen", answer: "to get excited" },
    { question: "Ausländer -", answer: "Foreigner (masc.)" },
    { question: "Ausländerin - nen", answer: "Foreigner (fem.)" },
    { question: "ausmachen", answer: "to turn (something) off" },
    { question: "ausprobieren", answer: "to try out" },
    { question: "ausschlafen", answer: "to have a good sleep" },
    { question: "außerdem", answer: "also" },
    { question: "aussprechen", answer: "to pronounce" },
    { question: "Auszubildende - n (der/die)", answer: "Apprentice" },
    { question: "Azubi - s", answer: "Apprentice (no gender)" },
    { question: "Becher - s", answer: "Cup" },
    { question: "Bedauern (Sg.)", answer: "Regret" },
    { question: "Behinderung - en", answer: "Disability" },
    { question: "Berufserhafrung (Sg.)", answer: "Job Experience" },
    { question: "Berufsleben (Sg.)", answer: "Job Life" },
    { question: "beruhigen", answer: "to calm down" },
    { question: "bestehen", answer: "passing (an exam)" },
    { question: "besuchen", answer: "to attend" },
    { question: "bewundern", answer: "to admire" },
    { question: "Bildschrim - e", answer: "Screen" },
    { question: "bisschen", answer: "a little" },
    { question: "Bitte - n", answer: "Request" },
    { question: "bitten", answer: "to request" },
    { question: "bloggen", answer: "to blog" },
    { question: "Bluse - n", answer: "Women's Jacket" },
    { question: "Brautpaar - e", answer: "Married Couple" },
    { question: "Bushaltestelle - n", answer: "Bus Stop" },
    { question: "checken", answer: "to check" },
    { question: "dabei sein", answer: "to be about" },
    { question: "Dauer (Sg.)", answer: "Duration" },
    { question: "dauern", answer: "to last" },
    { question: "dienen", answer: "to serve" },
    { question: "Direktor - en", answer: "School Principal (masc.)" },
    { question: "Direktorin - nen", answer: "School Principal (fem)" },
    { question: "downloaden", answer: "to download" },
    { question: "drehen", answer: "to record a video" },
    { question: "drucken", answer: "to print" },
    { question: "Drucker -", answer: "Printer" },
    { question: "dürfen", answer: "to be allowed" },
    { question: "ehrlich", answer: "honestly" },
    { question: "Emotion - en", answer: "Emotion" },
    { question: "Entscheidung", answer: "Decision" },
    { question: "Erfahrung - en", answer: "Experience" },
    { question: "Erholung (Sg.)", answer: "Relaxation" },
    { question: "Erinerung - en", answer: "Memory" },
    { question: "erschöpft", answer: "exhausted" },
    { question: "erst", answer: "only" },
    { question: "erst mal", answer: "first of all" },
    { question: "erwachsen", answer: "adult" },
    { question: "Fach -: er", answer: "School Subject" },
    { question: "fast", answer: "almost" },
    { question: "Ferien (Pl.)", answer: "School Break" },
    { question: "Fernsehgerät - e", answer: "Television Set" },
    { question: "fernsehen", answer: "to watch TV" },
    { question: "Feuerwerk - e", answer: "Firework" },
    { question: "Fotograf - en", answer: "Photographer (masc.)" },
    { question: "Fotografin - nen", answer: "Photographer (fem.)" },
    { question: "freiwillig", answer: "voluntary" },
    { question: "fremd", answer: "strange" },
    { question: "Fremdsprache - n", answer: "Foreign Language" },
    { question: "Freude - n", answer: "Joy" },
    { question: "furchtbar", answer: "terrible" },
    { question: "Führerschein - e", answer: "Driver's Licence" },
    { question: "gefährlich", answer: "dangerous" },
    { question: "Gefühl - e", answer: "Feeling" },
    { question: "Gegenteil - e", answer: "Opposite" },
    { question: "Gemeinsamkeit - en", answer: "Similarity" },
    { question: "genervt", answer: "annoyed" },
    { question: "gestresst", answer: "stressed" },
    { question: "gleich", answer: "same" },
    { question: "Glückwunschkarte - n", answer: "Congratulation card" },
    { question: "gratulieren", answer: "to congratulate" },
    { question: "Handwerk (Sg.)", answer: "Handcraft" },
    { question: "Hauptsache - n", answer: "Main Thing" },
    { question: "Heimat", answer: "Native" },
    { question: "Hemd - e", answer: "Men's Jacket" },
    { question: "hilfsbereit", answer: "helpful" },
    { question: "hoffen", answer: "to hope" },
    { question: "inzwischen", answer: "in the meantime" },
    { question: "je", answer: "each" },
    { question: "jobben", answer: "to work at a temporary job" },
    { question: "Jura", answer: "Law" },
    { question: "Karte - n", answer: "Card" },
    { question: "Kochrezept - e", answer: "Cooking Recipe" },
    { question: "Komödie - n", answer: "Comedy Film" },
    { question: "Konflikt - e", answer: "Conflict" },
    { question: "Kontakt - e", answer: "Contact" },
    { question: "kopieren", answer: "to copy" },
    { question: "kostenlos", answer: "free" },
    { question: "lachen", answer: "to laugh" },
    { question: "Laufwerk - e", answer: "Device" },
    { question: "Laune - n", answer: "Mood" },
    { question: "Lautsprecher -", answer: "Loudspeaker" },
    { question: "Lehre - n", answer: "Apprenticeship" },
    { question: "Lösung - en", answer: "Solution" },
    { question: "Maus -: e", answer: "Mouse" },
    { question: "Medaille - n", answer: "Medal" },
    { question: "Medien (Pl.)", answer: "Media" },
    { question: "Meinung", answer: "Opinion" },
    { question: "Messe - n", answer: "Fair" },
    { question: "Miete - n", answer: "Rent" },
    { question: "mindestens", answer: "at least" },
    { question: "mitkommen", answer: "to visit" },
    { question: "müde", answer: "tired" },
    { question: "nervös", answer: "nervous" },
    { question: "neugierig", answer: "curious" },
    { question: "niemand", answer: "nobody" },
    { question: "nirgends", answer: "nowhere" },
    { question: "noch", answer: "yet" },
    { question: "nützlich", answer: "useful" },
    { question: "online sein", answer: "to be online" },
    { question: "ordentlich", answer: "tidy" },
    { question: "Papier - e", answer: "Paper" },
    { question: "per", answer: "by" },
    { question: "Platz -: e", answer: "Place" },
    { question: "Praktikum, die Praktika", answer: "Practical Training" },
    { question: "praktisch", answer: "practical" },
    { question: "probieren", answer: "to try" },
    { question: "Produkt - e", answer: "Product" },
    { question: "Radio - s", answer: "Radio" },
    { question: "realistisch", answer: "realistic" },
    { question: "recherchieren", answer: "to research" },
    { question: "Regisseur - e", answer: "Film Director" },
    { question: "Reisebüro - s", answer: "Travel Agency" },
    { question: "riesen-", answer: "huge" },
    { question: "Ring - e", answer: "Ring" },
    { question: "Rollstuhl -: e", answer: "Wheelchair" },
    { question: "Romanze - n", answer: "Romance Film" },
    { question: "sauer", answer: "mad" },
    { question: "Schauspieler -", answer: "Actor" },
    { question: "Schauspielerin - nen", answer: "Actress" },
    { question: "schlecht", answer: "bad" },
    { question: "schlimm", answer: "terrible" },
    { question: "schmücken", answer: "to decorate" },
    { question: "schon", answer: "already" },
    { question: "Schulabschluss -: e", answer: "school graduation" },
    { question: "Schüler -", answer: "Pre-college Student (masc.)" },
    { question: "Schülerin - nen", answer: "Pre-college Student (fem.)" },
    { question: "Schüssel - n", answer: "Bowl" },
    { question: "selten", answer: "rarely" },
    { question: "senden", answer: "to send" },
    { question: "sich ärgern", answer: "to get angry" },
    { question: "sich ausruhen", answer: "to rest" },
    { question: "sich austauschen", answer: "to exchange ideas" },
    { question: "sich bedanken", answer: "to thank" },
    { question: "sich beschweren", answer: "to complain" },
    { question: "sich entscheiden", answer: "to decide" },
    { question: "sich entschuldigen bei + [Dativ]", answer: "to apologize from someone" },
    { question: "sich entschuldigen für [Akkusativ]", answer: "to apologize for something" },
    { question: "sich erinnern", answer: "to remember" },
    { question: "sich erinnern an + [Dativ]", answer: "to remember" },
    { question: "sich gewöhnen", answer: "to get used to" },
    { question: "sich interessieren für + [Akkusativ]", answer: "to have an interest for" },
    { question: "sich langweilen", answer: "to get bored" },
    { question: "sich streiten", answer: "to argue" },
    { question: "sich unterhalten", answer: "to talk" },
    { question: "sich wohlfühlen", answer: "to feel" },
    { question: "Sieg - e", answer: "Victory" },
    { question: "simsen", answer: "to text" },
    { question: "Smartphone - s", answer: "Smartphone" },
    { question: "spanned", answer: "exciting" },
    { question: "speichern", answer: "to save (a document)" },
    { question: "Spielekonsole - n", answer: "Game Console" },
    { question: "stehen", answer: "to stand" },
    { question: "stolz", answer: "proud" },
    { question: "stören", answer: "to disturb" },
    { question: "streng", answer: "strict" },
    { question: "sympatisch", answer: "sympathetic" },
    { question: "Tablet - s (der/das)", answer: "Tablet" },
    { question: "Tastatur - en", answer: "Keyboard" },
    { question: "teilnehmen an", answer: "to participate" },
    { question: "traurig", answer: "sad" },
    { question: "Umfrage - n", answer: "Survey" },
    { question: "unabhängig", answer: "independent" },
    { question: "unangenehm", answer: "not agreeable" },
    { question: "unglücklich", answer: "unlucky" },
    { question: "unterrichten", answer: "to educate" },
    { question: "Unterschied - e", answer: "Difference" },
    { question: "üben", answer: "to practice" },
    { question: "überall", answer: "everywhere" },
    { question: "überraschen", answer: "to surprise" },
    { question: "überrascht sein", answer: "to be surprised" },
    { question: "Verkehr (Sg.)", answer: "Traffic" },
    { question: "verlieren", answer: "to lose (something)" },
    { question: "verspätet", answer: "late" },
    { question: "Video - s", answer: "Video" },
    { question: "Vorbereitung - en", answer: "Preparation" },
    { question: "Vorlesung - en", answer: "University Lecture" },
    { question: "vorsichtig", answer: "careful" },
    { question: "Vorstellungsgespräch", answer: "Job Interview" },
    { question: "Vorurteil - e", answer: "Bias" },
    { question: "wahr", answer: "true" },
    { question: "wahrscheinlich", answer: "probably" },
    { question: "Währung - en", answer: "Currency" },
    { question: "wegfahren", answer: "to set off" },
    { question: "weinen", answer: "to cry" },
    { question: "Weltreise - n", answer: "World Trip" },
    { question: "weltweit", answer: "worldwide" },
    { question: "wenigstens", answer: "at least" },
    { question: "Werbeagentur - en", answer: "Advertising Agency" },
    { question: "wird herunterladen", answer: "to download" },
    { question: "witzig", answer: "funny" },
    { question: "Wohnheim - e", answer: "Dorm" },
    { question: "wütend", answer: "angry, furious" },
    { question: "Zeit verbringen", answer: "to spend time" },
    { question: "Zeitschrift - en", answer: "Magazine" },
    { question: "Zeugnis - se", answer: "Report Card" },
    { question: "ziemlich", answer: "rather, quite" },
    { question: "Zukunft (Sg.)", answer: "Future" },
    { question: "zurzeit", answer: "for now" },
    { question: "Zuschauer -", answer: "Audience Member (masc.)" },
    { question: "Zuschauerin - nen", answer: "Audience Member (fem.)" },
    { question: "zustimmen", answer: "to agree" }
];


let currentCard = {}; // Mevcut kartı tutacak değişken
let isFlipped = false; // Kartın şu an çevrili olup olmadığını takip etmek için

// Rastgele bir kart seçen fonksiyon
function getRandomCard() {
    const randomIndex = Math.floor(Math.random() * flashcards.length);
    return flashcards[randomIndex];
}

// Kartı gösteren fonksiyon
function showCard() {
    const frontElement = document.getElementById("front");
    const backElement = document.getElementById("back");

    currentCard = getRandomCard(); // Yeni bir rastgele kart seç
    
    // Almanca soruyu ve İngilizce cevabı güncelle
    frontElement.innerText = currentCard.question;
    backElement.innerText = "Click to reveal the answer"; // İlk başta İngilizce anlam gizli
}

// Kartı çevirme fonksiyonu
function flipCard() {
    const cardInner = document.getElementById("card-inner");
    const backElement = document.getElementById("back");

    if (!isFlipped) {
        // Kartı çevir ve İngilizce cevabı göster
        cardInner.classList.add("is-flipped");
        backElement.innerText = currentCard.answer; // İngilizce cevabı göster
        isFlipped = true; // Kart çevrildi
    } else {
        // Kartı geri çevir ve yeni bir kart göster
        cardInner.classList.remove("is-flipped");
        setTimeout(() => {
            showCard(); // Yeni kartı göstermeden önce birkaç saniye bekle
            isFlipped = false; // Kartı geri çevirdik
        }, 600); // Dönüş animasyonu için bekleme süresi
    }
}

// Sayfa yüklendiğinde ilk kartı göster
window.onload = showCard;
